# Generated by Django 5.1.5 on 2025-02-01 08:39

import django.contrib.auth.validators
import testapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_user_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='testapp_use_usernam_5d3377_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='testapp_use_email_2325cc_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='testapp_use_qr_code_a3b04d_idx',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='delivered',
            new_name='qr_delivered',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='verified',
            new_name='qr_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('volunteer', 'Volunteer')], default='participant', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(blank=True, default='default/default_profile.jpg', null=True, upload_to=testapp.models.user_image_upload_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
